# Generated by Django 5.0.3 on 2024-04-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('adopt_id', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=255)),
                ('pets', models.IntegerField()),
                ('phoneNumber', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
