# Generated by Django 5.0.3 on 2024-05-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('vet_id', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('businessName', models.CharField(max_length=255)),
            ],
        ),
    ]
