# Generated by Django 5.0.3 on 2024-04-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('shelter_id', models.IntegerField()),
                ('species', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('adoptered', models.BooleanField(default=False)),
                ('worker_id', models.IntegerField()),
                ('vet_id', models.IntegerField(blank=True, null=True)),
                ('adopt_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
