# Generated by Django 5.0.3 on 2024-04-27 21:32

import pet_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_path',
            field=models.CharField(blank=True, default=pet_page.models.default_pet_image, max_length=255, null=True),
        ),
    ]
