# Generated by Django 5.0.3 on 2024-05-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_page', '0003_remove_pet_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_path',
            field=models.CharField(default='/static/images/default.jpg', max_length=255),
        ),
    ]
